pipeline {
    agent {
        docker {
            image 'maven:3.8.1-adoptopenjdk-11'
            args '-v /root/.m2:/root/.m2'
        }
    }
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage ('Build') {
         steps {
              sh 'mvn clean install -f pom.xml'
            }
        }
        stage('Build and test for deployment') {
            steps {
                withSonarQubeEnv(installationName: 'sonar-server', credentialsId: 'token') {
                sh 'mvn -B -DskipTests clean package sonar:sonar'
                
                echo "build and test"
            }
        }
             
      }
        stage("Quality gate with test-way condirion") {
            steps {
                waitForQualityGate abortPipeline: true
            }
        }
        stage('Deliver on success to console') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
    }
}
