pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /jenkins/.m2:/jenkins/.m2'
        }
    }
    stages {
        stage ('Scan and Build Jar File') {
            steps {
               withSonarQubeEnv('sonar-server') {
                sh 'mvn clean package sonar:sonar'
                }
            }
        }
        
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        
        
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
